!Write a program which will read a file containing book references, will select those that
!contain a character string specified by the user and will print the selected references to
!another file.
!the file has the structure
!Title,Author,Year,ISBN-13
!each field is separated by commas
PROGRAM books
  IMPLICIT NONE
  INTEGER :: MDIM,N,I
  CHARACTER*80 :: IFNAM
! N=ACTUAL NUMBER OF BOOKS IN CATALOGUE
! MDIM=MAX. DIMENSION OF THE BOOK COLLECTION
  PARAMETER(MDIM=32)
  CHARACTER*16 :: STR
! STR to search among titles
  CHARACTER*32 :: TITLE(MDIM)
  CHARACTER*32 :: AUTHOR(MDIM) ! NAME SURNAME
  INTEGER YEAR(MDIM)
  CHARACTER*14 ISBN13(MDIM)
  COMMON /CATALOG/TITLE,AUTHOR,YEAR,ISBN13,N
  N=MDIM
  PRINT *,'ENTER THE NAME OF THE FILE TO READ'
  READ *,IFNAM
  CALL load_books(IFNAM)
  DO I=1,N
    PRINT 100, I,TITLE(I),AUTHOR(I),YEAR(I),ISBN13(I)
  END DO
  PRINT *,'PLEASE SELECT A STRING TO SEARCH IN TITLES'
  READ *,STR
  CALL save_selected(STR)
100 FORMAT(I4,1X,A32,1X,A32,1X,I4,1X,A14)
  STOP
END PROGRAM books

SUBROUTINE load_books(IFNAM)
  IMPLICIT NONE
! MDIM=MAX. DIMENSION OF THE BOOK COLLECTION
  INTEGER :: N
! N=ACTUAL NUMBER OF BOOKS IN CATALOGUE
  CHARACTER*80,INTENT(IN) :: IFNAM
  LOGICAL DEBUG
  INTEGER :: MDIM,POSI
  PARAMETER(MDIM=32)
  CHARACTER*90 LINE
  CHARACTER*32 :: TITLE(MDIM)
  CHARACTER*32 :: AUTHOR(MDIM) ! NAME SURNAME
  INTEGER YEAR(MDIM)
  CHARACTER*14 ISBN13(MDIM)
  COMMON /CATALOG/TITLE,AUTHOR,YEAR,ISBN13,N
  DEBUG=.FALSE.
  OPEN(11,FILE=IFNAM,ERR=9000)
  !remove the first line
  READ(11,'(A)',END=80,ERR=9100) LINE
  IF (DEBUG) PRINT *,'LINE = ',LINE
  DO N=1,MDIM
    READ(11,'(A)',END=80,ERR=9100) LINE
    IF (DEBUG) PRINT *,N,'LINE = ',LINE
    ! find the position of the comma ,
    POSI=INDEX(LINE,',')
    TITLE(N)=LINE(1:POSI-1)
    LINE=LINE(POSI+1:)
    POSI=INDEX(LINE,',')
    AUTHOR(N)=LINE(1:POSI-1)    
    LINE=LINE(POSI+1:)
    POSI=INDEX(LINE,',')
    READ(LINE(1:POSI-1),'(I4)',ERR=9200)YEAR(N)
    LINE=LINE(POSI+1:)
    ISBN13(N)=LINE
  END DO
80  CLOSE(11)
  N=N-1
  PRINT *,'N. OF BOOKS IN CATALOGUE: ',N
  GOTO 9999
9000 PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
  GOTO 9999
9100 PRINT *,'ERROR IN READING RECORD ',N
  GOTO 9999
9200 PRINT *,'ERROR IN READING YEAR FIELD, RECORD ',N
9999 RETURN
END SUBROUTINE load_books

SUBROUTINE save_selected(STR)
  CHARACTER*80 :: OFNAM
  INTEGER :: MDIM,I,POSI
  PARAMETER(MDIM=32)
! N=ACTUAL NUMBER OF BOOKS IN CATALOGUE
! MDIM=MAX. DIMENSION OF THE BOOK COLLECTION
  CHARACTER*16 :: STR
! STR to search among titles
  CHARACTER*32 :: TITLE(MDIM)
  CHARACTER*32 :: AUTHOR(MDIM) ! NAME SURNAME
  INTEGER YEAR(MDIM)
  CHARACTER*14 ISBN13(MDIM)
  LOGICAL DEBUG
  COMMON /CATALOG/TITLE,AUTHOR,YEAR,ISBN13,N
  DEBUG=.FALSE.
  OFNAM='selected_books.csv'
  IF (DEBUG) PRINT *,'going to search through ',N,'books'
  OPEN(11,FILE=OFNAM,ERR=9000)
  DO I=1,N
    IF (DEBUG) PRINT *,I,'searching if title "',TRIM(TITLE(I)),'" contains ',TRIM(STR)
    POSI=INDEX(TITLE(I),TRIM(STR))
    IF (DEBUG) PRINT *,'POSI = ',POSI
    IF (POSI.GT.0) THEN
	  WRITE(11,'(I4,1X,A14)',ERR=9100) I,ISBN13(I)
    ELSE
      CONTINUE
    END IF
  END DO
  CLOSE(11)
  GOTO 9999
9000 PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
  GOTO 9999
9100 PRINT *,'ERROR IN WRITING DATA AT RECORD ',I
9999 RETURN
END SUBROUTINE
