C PROGRAM THAT READS IN A NUMBER, AND COMPUTES THE AREA OF A CIRCLE THAT HAS A
C DIAMETER OF THAT SIZE.
      PROGRAM CIRCLE
        REAL D,AREA,PI
        PARAMETER(PI=3.1415927)
        PRINT *,'GIVE ME THE DIAMETER OF THE CIRCLE'
        READ *,D
        AREA = PI*(D/2.0)**2
        PRINT '(A,F12.6)','THE AREA OF THE CIRCLE IS',AREA
        STOP
      END
