      PROGRAM COMM
       INTEGER WIDTH,HEIGHT
       INTEGER ARR(200,300)
       COMMON /MATRIX/ WIDTH,HEIGHT,ARR
       WIDTH=300
       HEIGHT=200
       CALL FILARR
       CALL SHOW
       STOP
      END
C
      SUBROUTINE FILARR
       INTEGER WIDTH,HEIGHT,I,J
       INTEGER ARR(200,300)
       COMMON /MATRIX/ WIDTH,HEIGHT,ARR
       DO 10,J=1,HEIGHT
         DO 20,I=1,WIDTH
           PRINT *,(J-1)*WIDTH+I
           ARR(J,I)=(J-1)*WIDTH+I
20       CONTINUE
10     CONTINUE
      END
C
      SUBROUTINE SHOW
       INTEGER WIDTH,HEIGHT,I,J
       INTEGER ARR(200,300)
       CHARACTER*1200 LINE
       COMMON /MATRIX/ WIDTH,HEIGHT,ARR
       DO 10,J=1,HEIGHT
         DO 20,I=1,WIDTH
           WRITE(LINE(4*(I-1)+1:4*(I-1)+4),'(I3,1X)')
     & MOD(ARR(J,I),256)
20       CONTINUE
         PRINT '(A1200)',LINE
10     CONTINUE
      END
C
      SUBROUTINE SUB3
      END
