      PROGRAM ENDF
        IMPLICIT NONE
        CHARACTER*64 IFNAM,OFNAM
        CHARACTER*1024 LINE
        INTEGER I,IOS,FIOS,POSI
        PRINT *,'ENTER INPUT FILE NAME'
        READ *,IFNAM
        POSI=INDEX(IFNAM,'.')
        OFNAM=IFNAM(1:POSI)//'bin'
        I=1
        OPEN(11,FILE=IFNAM,ERR=8000)
        OPEN(12,FILE=OFNAM,FORM='UNFORMATTED',ACCESS='DIRECT',ERR=8100
     & ,RECL=80)
10      READ(11,'(A)',END=80,ERR=9000,IOSTAT=IOS) LINE
          PRINT *,'LINE ',I,': ',LINE(1:80)
          WRITE(12,REC=I,ERR=9100,IOSTAT=FIOS) LINE(1:80)
C          IF(I.EQ.6) THEN 
C             BACKSPACE(11)
c            ENDFILE(11)
c            REWIND(11)
C          END IF
          I=I+1
        GOTO 10
80      CLOSE(11)
        CLOSE(12)  
        PRINT *,'END OF FILE REACHED: EXITING'
        GOTO 9999
8000    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM
        GOTO 9999
8100    PRINT *,'ERROR IN OPENING OUTPUT FILE ',OFNAM
        GOTO 9999
9000    PRINT 100,I,IOS
        GOTO 9999
9100    PRINT 200,I,FIOS
9999    STOP
100     FORMAT('ERROR IN READING LINE',I4,' IOSTAT: ',I4)
200     FORMAT('ERROR IN WRITING LINE',I4,' IOSTAT: ',I4)
      END
