!Write a program to generate the Fibonacci sequence of numbers,
! 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, etc.
!until the absolute value of the difference between the ratio of two consecutive numbers
! x_(n+1)/x_n and the Golden Ratio (√5+1)/2 is less than some arbitrary small value ε.
! abs(x_(n+1)/x_n - (√5+1)/2) < ε
! The Fibonacci sequence is generated by the formula
! x_(n+1) = x_n + x_(n−1) , n = 1, 2, . . .
!
! This program illustrates that the ratio of two consecutive
! numbers of the Fibonacci sequence converges to the
! Golden-Ratio
!
PROGRAM SHOW_FIBO
   IMPLICIT NONE
   INTEGER :: N,F,FIBO
   CALL SET_DATA
   CALL SHOW_CRIT
10 PRINT *,'COMPUTE FIBONACCI SERIES'
   PRINT *,'ENTER A POSITIVE INTEGER NUMBER (-1 to stop)'
   READ *,N
   IF (N.EQ.-1) GOTO 9999
   F=FIBO(N)
   PRINT 100,N,F
   GOTO 10
100 FORMAT('FIBO(',I4,')=',I7)
9999 STOP
END PROGRAM SHOW_FIBO

SUBROUTINE SHOW_CRIT
  IMPLICIT NONE
  INTEGER :: I,MAXDIM,FIBO
  PARAMETER(MAXDIM=32)
  REAL :: EPS,CRIT(MAXDIM)
  PARAMETER(EPS=1E-7)
  DO I=1,MAXDIM
	CRIT(I)=ABS(REAL(FIBO(I+1))/REAL(FIBO(I))-((5**0.5)+1.0)/2.0)
	IF (CRIT(I).GT.EPS) THEN 
	  PRINT *,I,CRIT(I)
	ELSE
	  EXIT
	END IF
  END DO
  RETURN
END SUBROUTINE SHOW_CRIT

SUBROUTINE SET_DATA
  IMPLICIT NONE
  INTEGER :: I,MAXDIM
  PARAMETER(MAXDIM=32)
  INTEGER FI(0:MAXDIM)
  COMMON /FIDATA/FI
  DO I=0,MAXDIM
	  IF (I.EQ.0) THEN
	    FI(I)=0
	  ELSE IF (I.EQ.1) THEN
	    FI(I)=1
	  ELSE	
		FI(I)=FI(I-1)+FI(I-2)
	  END IF
  END DO
END SUBROUTINE SET_DATA

INTEGER FUNCTION FIBO(N)
  IMPLICIT NONE
  INTEGER N,MAXDIM
  PARAMETER(MAXDIM=32)
  INTEGER FI(0:MAXDIM)
  COMMON /FIDATA/FI
  FIBO=FI(N)
  RETURN
END FUNCTION FIBO
