      PROGRAM IOSTA
C READING AN ASCII PIXEL LIST IMAGE
        IMPLICIT NONE
        CHARACTER*128 IFNAM
        INTEGER I,MAXDIM,IOS
        PARAMETER(MAXDIM=500)
        INTEGER X(MAXDIM**2),Y(MAXDIM**2),VALUES(MAXDIM**2)
        LOGICAL DEBUG,E
C THIS PROGRAM SHOWS THE USAGE OF IOSTAT SPECIFIER
        PRINT *,'ENTER INPUT FILENAME'
        READ (*,*,END=9000,ERR=9100) IFNAM
        I=1
        INQUIRE(FILE=IFNAM,EXIST=E)
        IF(.NOT.E) THEN 
          PRINT *,'DOES THE FILE ',IFNAM(1:16),'EXIST?'
          GOTO 9200
        END IF
        OPEN(11,FILE=IFNAM,ERR=9200)
10      READ(11,FMT=100,END=80,IOSTAT=IOS,ERR=9400)
     & X(I),Y(I),VALUES(I)
          IF(IOS.LT.0) THEN
             PRINT *,'END OF FILE REACHED: IOS = ',IOS
          ELSE IF(IOS.GT.0) THEN
            PRINT *,'ERROR IN READING ROW: IOS = ',IOS,
     & 'AT FILE ROW = ',I
          END IF
          I=I+1
        GOTO 10
80      CLOSE(11)
        PRINT *,'END OF FILE ',IFNAM(1:16),' REACHED,IOSTAT =',IOS
        PRINT *,'READ ',I-1,' FILE ROWS/ELEMENTS'
        IF(Y(I-1).GT.0) PRINT *,'IMAGE WIDTH IS ',(I-1)/Y(I-1)
        PRINT *,'IMAGE HEIGHT IS ',Y(I-1)
        GOTO 9999
100     FORMAT(I5,1X,I5,1X,I3)
9000    PRINT *,'INPUT FILE NAME NOT RECEIVED: EXITING'
        GOTO 9999
9100    PRINT *,'ERROR IN READING INPUT FILE NAME: EXITING'
        GOTO 9999
9200    PRINT *,'ERROR IN OPENING INPUT FILE ',IFNAM(1:16)
        GOTO 9999
9400    PRINT *,'ERROR IN READING DATA ROW n. ',I,' IOS = ',IOS
9999    STOP
      END
