      PROGRAM logic
        IMPLICIT NONE
        INTEGER I
        CHARACTER*80 IFNAM
        LOGICAL LV(10)
        DATA LV/.TRUE.,.TRUE.,.FALSE.,.TRUE.,.FALSE.,.FALSE.,.FALSE.,
     &.TRUE.,.FALSE.,.TRUE./
C        CALL CD(LV)
C        STOP
        PRINT *,'ENTER FILE NAME TO READ'
        READ *, IFNAM
        CALL LD(LV,IFNAM)
        DO 10,I=1,10
          IF(LV(I)) THEN
            PRINT *,I,'.TRUE.'
          ELSE IF (.NOT.LV(I)) THEN
            PRINT *,I,'.FALSE.'
          ELSE
            PRINT *,'SOMETHING STRANGE HAS BEEN READ'
          END IF
10      CONTINUE
        GOTO 9999
9999    STOP
      END
C LD: LOAD DATA
      SUBROUTINE LD(LV,IFNAM)
        IMPLICIT NONE
        CHARACTER*80 IFNAM
        LOGICAL LV(10)
        OPEN(11,FILE=IFNAM,ERR=9000)
        READ(11,100,ERR=9100,END=9200) LV
        CLOSE(11)
        GOTO 9999
100     FORMAT(9(L1,1X),L1)
9000    PRINT *,'ERROR IN OPENING INPUT FILE',IFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN READING DATA'
        GOTO 9999
9200    PRINT *,'END OF FILE REACHED'
9999    RETURN        
      END
C CD: CREATE DATA
      SUBROUTINE CD(LV)
        IMPLICIT NONE
        LOGICAL LV(10)
        CHARACTER*80 OFNAM
        PRINT *,'ENTER OUTPUT FILE NAME'
        READ *,OFNAM
        OPEN(11,FILE=OFNAM,ERR=9000)
        WRITE(11,100,ERR=9100) LV
        CLOSE(11)
        GOTO 9999
100     FORMAT(9(L1,','),L1)
9000    PRINT *,'ERROR IN OPENING OUTPUT FILE',OFNAM
        GOTO 9999
9100    PRINT *,'ERROR IN WRITING DATA'
9999    RETURN
      END
