FC=ftn77
FD=slink
F95=ftn95
OEXT=.obj
EEXT=.exe
RM=del /Q /F
ROOT=
FFLAGS=
ROOT=
FDFLAGS=
LIBS=
SRCS=common.f limits.f iostat.f endfile.f endf2unf.f readunf1.f append.f files.f sort.f in2files.f \
pi.f fun100.f fun101.f fun102.f readfun.f butterfly.f chaos.f euclid.f r2b.f blockdata.f taysin.f \
form001.f entry.f expand.f wrtdat.f
OBJS = $(SRCS:.f=$(OEXT))
TARGETS = $(OBJS:$(OEXT)=$(EEXT)) tracker$(EEXT) entry002$(EEXT) external$(EEXT)
.PHONY: all clean

all: $(OBJS) $(TARGETS)

%$(OEXT): %.f
	$(FC) $(FFLAGS) $< /LIST

%$(EEXT): %$(OEXT)
	$(FD) -OUT:$@ $^ $(LIBS) $(FDFLAGS)

tracker$(EEXT): tracker.f95
	$(F95) $< /LINK /o $@

entry002$(EEXT): entry002.f95
	$(F95) $< /LINK /o $@

external$(EEXT): external.f95
	$(F95) $< /LINK /o $@
clean:
	$(RM) $(OBJS) $(TARGETS) tracker$(EEXT) entry002$(EEXT) external$(EEXT)

