FC=ftn77
FD=slink
OEXT=.obj
EEXT=.exe
RM=del /Q /F
ROOT=
FFLAGS=
ROOT=
FDFLAGS=
LIBS=
FDFLAGS=
LIBS=
SRCS=common.f limits.f iostat.f endfile.f endf2unf.f readunf1.f
OBJS = $(SRCS:.f=$(OEXT))
TARGETS = $(OBJS:$(OEXT)=$(EEXT))
.PHONY: all clean

all: $(OBJS) $(TARGETS)

%$(OEXT): %.f
	$(FC) $(FFLAGS) $< /LIST

%$(EEXT): %$(OEXT)
	$(FD) -OUT:$@ $^ $(LIBS) $(FDFLAGS)

clean:
	$(RM) $(OBJS) $(TARGETS)

