!program that reads in a series of integer numbers, and determines how many
!positive odd numbers are among them. Numbers are read until a negative integer is
!given. Use cycle and exit.
PROGRAM ODDS
  IMPLICIT NONE
  CHARACTER*80 :: IFNAM
  PRINT *,'ENTER NAME OF INPUT FILE'
  READ(*,*,ERR=9000) IFNAM
!  CALL INI_RAN
!  CALL CNL(IFNAM,2048)
  CALL CON(IFNAM)
  GOTO 9999
9000 PRINT *,'ERROR IN READING FILE NAME'
9999 STOP
END PROGRAM ODDS
! CNL: Create Number List
SUBROUTINE CNL(OFNAM,N)
  IMPLICIT NONE
  REAL :: GETRAN
  INTEGER :: N,I
  CHARACTER*80 :: OFNAM
  OPEN(11,FILE=OFNAM,ERR=9000)
  DO I=1,N
    WRITE(11,'(I4)',ERR=9100) NINT(GETRAN(2048.0)+1024)
  END DO
    WRITE(11,'(I4)',ERR=9100) -1
  CLOSE(11)
  GOTO 9999
9000 PRINT *,'ERROR IN OPENING OUTPUT FILE',OFNAM
  GOTO 9999
9100 PRINT *,'ERROR IN WRITING DATA'
9999 RETURN
END SUBROUTINE CNL
!CON: Count Odd Numbers
SUBROUTINE CON(IFNAM)
  IMPLICIT NONE
  INTEGER :: N,CNT,V
  CHARACTER*80 :: IFNAM
  CNT=0
  OPEN(11,FILE=IFNAM,ERR=9000)
  DO
    READ(11,'(I4)',ERR=9100) V
    IF (V.LT.0) THEN
      EXIT
    ELSE IF(MOD(V,2).EQ.0) THEN
      CYCLE
    END IF
    CNT=CNT+1
  END DO
  CLOSE(11)
  PRINT *,'READ ',CNT,'ODD NUMBERS'
  GOTO 9999
9000 PRINT *,'ERROR IN OPENING INPUT FILE',IFNAM
  GOTO 9999
9100 PRINT *,'ERROR IN READING DATA'
9999 RETURN
END SUBROUTINE CON
