C PROGRAM SHOWING THE USAGE OF BLOCK DATA SUBPROGRAM
C
      PROGRAM LOADDB
        CHARACTER *80 IFNAM
        PRINT *,'TYPE FILE NAME FROM WICH READING CONTACTS'
        READ *,IFNAM
        CALL LDRECS(IFNAM)
        STOP
      END   

