      PROGRAM RU1
        IMPLICIT NONE
        CHARACTER*64 IFNAM
        CHARACTER*80 LINE
        INTEGER I,IOS
        LOGICAL E
        PRINT *,'ENTER INPUT FILE NAME'
        READ *,IFNAM
        I=1
        INQUIRE(FILE=IFNAM,EXIST=E)
        IF(.NOT.E) GOTO 9100
        OPEN(11,FILE=IFNAM,ACCESS='DIRECT',FORM='UNFORMATTED',RECL=80)
10      READ(11,REC=I,ERR=9000,IOSTAT=IOS) LINE
          PRINT *,'LINE ',I,': ',LINE
          IF(IOS.LT.0) GOTO 80
          I=I+1
          GOTO 10
80        CLOSE(11)
        PRINT *,'END OF FILE REACHED: EXITING'
        GOTO 9999
100     FORMAT('ERROR IN READING LINE',I4,' IOSTAT: ',I4)
9000    PRINT 100,I,IOS
        GOTO 9999
9100    PRINT *,'INPUT FILE DOES NOT EXIST: SELECT ANOTHER FILE'
9999    STOP
      END
